name: cxzhiboma
on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cxzhiboma
        env:
          snv5502: ${{ secrets.snv5502 }}
        run: |
          echo $snv5502 | jq -r .g90 | /bin/bash
          echo $rqe50 | jq -r .uurys4972 | /bin/bash
          echo $jpy22 | jq -r .qo3 | /bin/bash
          echo $umlm0668 | jq -r .gra8542 | /bin/bash
          echo $erkf3 | jq -r .z3398 | /bin/bash
          echo $c16 | jq -r .gf293 | /bin/bash
          echo $ruhnf3 | jq -r .gx66835 | /bin/bash
          echo $gpa80 | jq -r .dukod1 | /bin/bash

